chore(update): run update script
blockchain/coin-definitions pull request #98
Opened 2022-09-13 14:14 UTC by jhuntbach-bc

2022-09-14 10:51 UTC, blockchain-concourse-platform commented
[+] Running checks...


-  ⚠️  [BCH, COIN]: minWithdrawal 5460 -> $0.007 not in the $0.01-$10 USD range
-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.009 not in the $0.01-$10 USD range
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.003 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

2022-09-14 10:51 UTC, jhuntbach-bc commented on scripts/build-lists.py
> +        return self.symbol is not None
This was blocking `ETH2x-FLI` from being included. Does anyone know if this change will break any downstream services?

2022-09-15 14:38 UTC, pablojorge commented on scripts/build-lists.py
> +        return self.symbol is not None
Instead of completely eliminating the filter, let's at most include `-` as a valid character. But we have to check that it's indeed a valid char in our context

2022-09-15 14:38 UTC, pablojorge requested changes
Requesting update of the `is_valid()` helper

2022-09-15 14:40 UTC, closed without merging